language: objective-c

cache: bundler

rvm:
  - 2.0.0

before_install:
    - bundle install --deployment --local --no-cache
    - bundle exec rake install

script:
    - kitchenplan setup https://github.com/kitchenplan/kitchenplan-config-test.git
    - kitchenplan provision
#    - sudo rake test
