groups:
    - smarties
recipes:
    mac_os_x:
        - applications::1password
attributes:
    rvm:
        user_installs:
            -
                user: travis
                upgrade: head
                default_ruby: 1.9.3-p385
    git:
        name: Travis
        email: roderik+travis@vanderveer.be
    osxdefaults:
        computername: TravisWorker
    dotfiles:
        kdeploy:
            hostname: travisworker.dev
