groups:
    - smarties
recipes:
    mac_os_x:
        - applications::1password
attributes:
    git:
        name: Travis
        email: roderik+travis@vanderveer.be
    osxdefaults:
        computername: TravisWorker
    dotfiles:
        kdeploy:
            hostname: travisworker.dev
