groups:
    - smarties
recipes:
    mac_os_x:
        - applications::1password
attributes:
    git:
        name: Vagrant
        email: roderik+vagrant@vanderveer.be
    osxdefaults:
        computername: VagrantQuantal64
    dotfiles:
        kdeploy:
            hostname: quantal64.dev
