recipes:
    global:
        - applications::create_var_chef_cache
        - applications::google-chrome
        - applications::firefox
        - kono_workstation::java
        - applications::vlc
        - applications::flash
        - applications::adobe_reader
    mac_os_x:
        - drivers::xerox550
attributes:
    drivers:
        xerox: 172.18.19.67
